language: java
install: skip
jdk: openjdk8
jobs:
   include:
     - stage: Build
       script: gradle clean build
       
     - stage: Test
       script: gradle test jacocoTestReport coverall
     
     - stage: Run Linter
       script: gradle checkstyleMain