language: java
install: skip
jdk: oraclejdk8
jobs:
   include:
     - stage: Build
       script: gradle clean build
       
     - stage: Test
       script: gradle test
       
     - stage: Generate jacoco reports
       script: gradle jacocoTestReport
     
     - stage: Run Linter
       script: gradle checkstyleMain