language: java
install: skip
jdk: openjdk8
jobs:
   include:
     - stage: Build
       script: gradle clean build
       
     - stage: Test
       script: gradle test jacocoTestReport coverall
     
     - stage: Run Sonar
       script: gradle sonarqube
     
     - stage: Publish to Github
       script: gradle publish
addons:
  sonarcloud:
    organization: "liamncat"
    token:
      secure: "f207bd94d79b09e8f083064a2c66e924608cf624"